fix: export memblock_free
This is required for drivers/gpu/drm/rockchip/rockchip_drm_logo.c to compile properly as a module.

Without this patch, build including rockchip-drm fail for me with

ERROR: modpost: "memblock_free" undefined!

cherry-picked from https://android.googlesource.com/kernel/common/+/cd5f5cb9fe677466551e44039b31198e7b0dc812%5E%21/